### ISSUE TITLE
Could you please tell me how to get the text features?

### ISSUE THREAD

**Issue by ThBird** [xian-sh/UniSDNet#1]

**Comment by xian-sh** [comment]
Text features can be extracted using the code given in the ''pre_process/text_encode.py'' file, GloVe or DistilBert, which doesn't take too much time.

**Comment by ThBird** [comment]
> Text features can be extracted using the code given in the ''pre_process/text_encode.py'' file, GloVe or DistilBert, which doesn't take too much time.

OK, Thanks for your reply!
